gestion_projet:
    resource: "@GestionProjetBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /


article:
    resource: "@BackBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article
    
reference:
    resource: "@BackBundle/Resources/config/routing/reference.yml"
    prefix:   /admin/reference  
    
electricite:
    resource: "@BackBundle/Resources/config/routing/electricite.yml"
    prefix:   /admin/electricite 
    
batiment:
    resource: "@BackBundle/Resources/config/routing/batiment.yml"
    prefix:   /admin/batiment
    
    