admin Articles_index:
    path:     /
    defaults: { _controller: "BackBundle:Article:index" }
    methods:  GET

admin Articles_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Article:show" }
    methods:  GET

admin Articles_new:
    path:     /new
    defaults: { _controller: "BackBundle:Article:new" }
    methods:  [GET, POST]

admin Articles_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Article:edit" }
    methods:  [GET, POST]

admin Articles_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Article:delete" }
    methods:  DELETE

admin Articles_modifier:
    path:     /modifier
    defaults: { _controller: "BackBundle:Article:modifier" }
    
admin Articles_recherche:
    path:     /recherche
    defaults: { _controller: "BackBundle:Article:recherche" }      