<?php

namespace Myapp\BackBundle\Repository;

/**
 * electriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class electriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
