<?php

namespace Myapp\BackBundle\Repository;

/**
 * ElectriciteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectriciteRepository extends \Doctrine\ORM\EntityRepository
{
   public function findElectricitesBytitre($titre){
        
    $query = $this->createQueryBuilder('a')
    ->where('a.titre like :titre')
    ->setParameter('titre', $titre.'%')
    ->orderBy('a.titre', 'ASC')
    ->getQuery();

     return  $query->getResult();
          
          
          
          
}
}
