gestion_projet_homepage:
    path:     /
    defaults: { _controller: GestionProjetBundle:Default:index }

acceuil:
    path:     /acceuil
    defaults: { _controller: GestionProjetBundle:Default:acceuil }  
    
about:
    path:     /about
    defaults: { _controller: GestionProjetBundle:Default:about} 
    
batiment:
    path:     /batiment
    defaults: { _controller: GestionProjetBundle:Default:batiment}   
    
electricite:
    path:     /electricite
    defaults: { _controller: GestionProjetBundle:Default:electricite}     